### ISSUE TITLE
Ukulele/ukelele

### ISSUE THREAD

**Issue by RobColes** [egradman/scales-chords#3]
I couldn't get the ukulele tabs to show. I'm not sure if this is because of a typo - "ukelele" in the doco. I tried both but couldn't see any chords. 

I can see the chords, but no fretboard layout if I go to ScalesChords.

**Comment by jchenibm** [comment]
same issue here

**Comment by MisterTeatime** [comment]
I also got the extension for the ukulele option.

Looking at the API chords seem only available for piano and guitar. 

> Optional field: instrument="guitar or piano"
> This field defines if the image (chord chart) or sound that you want is por piano or guitar. If this field is not defined it defaults to instrument="guitar"
> Example: instrument="piano"

[Scale-Chords API reference](https://www.scales-chords.com/api/#reference)

**Comment by egradman** [comment]
hey y'all, sorry I haven't taken a look at this.  It seems like @MisterTeatime has found the issue.  I rely on the Scales and Chords API to translate a `(instrument, chord)` pair into an image URL.  If their API doesn't support ukelele, then there's nothing I can do.

They have a feedback form on that API reference page.  If they ever update their API to support ukelele, then this plugin should "just work" without updates.
